[run]
tests = false

[linters]
enable-all = true
disable = [
  "maligned",
  "scopelint",
  "golint",
  "interfacer",

  "exhaustivestruct",
  "goerr113",
  "gochecknoglobals",
  "gomnd",

  "cyclop",
  "funlen",
  "gocognit",
  "gocyclo",
]

[linters-settings.gocognit]
min-complexity = 10

[linters-settings.gocyclo]
min-complexity = 15
