---
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go mod vendor

builds:
  - goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=vendor
    main: ./cmd/merje
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge pull request"