---
name: versioning

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: semantic
      - uses: actions/setup-go@v3
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          go-version: 1.18.x
      - uses: actions/cache@v3
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: goreleaser/goreleaser-action@v2
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          version: latest
          args: release --rm-dist
          workdir: v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
